pkg_name:       "MY_EXAMPLE"
pkg_usr:        "MY_USER"
beam_path:      "BEAM_PATH"
conf_dir:       "/CONFIG"
config_dir:     "/CONFIG_DIR"
bin_path:       "BIN"
conf_dir_var:   "CONF_DIR_VAR"
daemon_flags:   ""
env_file_name:  "ENV_FILE_NAME"
var_dir:        ""
pkg_prefix:     ""
